logging:
  level:
    io.opentelemetry: DEBUG
    dev.danvega: INFO
    org.springframework.boot.actuator.autoconfigure.opentelemetry: DEBUG
    org.springframework.boot.docker.compose: DEBUG

server:
  port: 8084
  shutdown: immediate

spring:
  application:
    name: library-events-db

management:
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for development
    propagation:
      type: W3C
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
